export const users = [
  { id: 1, name: "John Doe", email: "john.doe@example.com" },
  { id: 2, name: "Jane Smith", email: "jane.smith@example.com" },
  { id: 3, name: "Alice Johnson", email: "alice.johnson@example.com" },
  { id: 4, name: "Bob Williams", email: "bob.williams@example.com" },
  { id: 5, name: "Charlie Brown", email: "charlie.brown@example.com" },
  { id: 6, name: "Diana Prince", email: "diana.prince@example.com" },
  { id: 7, name: "Eve Adams", email: "eve.adams@example.com" },
  { id: 8, name: "Frank Miller", email: "frank.miller@example.com" },
  { id: 9, name: "Grace Lee", email: "grace.lee@example.com" },
  { id: 10, name: "Henry Ford", email: "henry.ford@example.com" },
  { id: 11, name: "Ivy Clark", email: "ivy.clark@example.com" },
  { id: 12, name: "Jack White", email: "jack.white@example.com" },
  { id: 13, name: "Karen Black", email: "karen.black@example.com" },
  { id: 14, name: "Leo King", email: "leo.king@example.com" },
  { id: 15, name: "Mona Green", email: "mona.green@example.com" },
  { id: 16, name: "Nina Scott", email: "nina.scott@example.com" },
  { id: 17, name: "Oscar Young", email: "oscar.young@example.com" },
  { id: 18, name: "Paul Hall", email: "paul.hall@example.com" },
  { id: 19, name: "Quinn Reed", email: "quinn.reed@example.com" },
  { id: 20, name: "Rita Bell", email: "rita.bell@example.com" },
  { id: 21, name: "Sam Fox", email: "sam.fox@example.com" },
  { id: 22, name: "Tina Wood", email: "tina.wood@example.com" },
  { id: 23, name: "Uma Stone", email: "uma.stone@example.com" },
  { id: 24, name: "Vera Lane", email: "vera.lane@example.com" },
  { id: 25, name: "Will Page", email: "will.page@example.com" },
  { id: 26, name: "Xena Ray", email: "xena.ray@example.com" },
  { id: 27, name: "Yara Moss", email: "yara.moss@example.com" },
  { id: 28, name: "Zane Cole", email: "zane.cole@example.com" },
  { id: 29, name: "Brady Nash", email: "brady.nash@example.com" },
  { id: 30, name: "Cora Lane", email: "cora.lane@example.com" },
  { id: 31, name: "Derek Shaw", email: "derek.shaw@example.com" },
  { id: 32, name: "Elena Park", email: "elena.park@example.com" },
  { id: 33, name: "Felix Boyd", email: "felix.boyd@example.com" },
  { id: 34, name: "Gina Holt", email: "gina.holt@example.com" },
  { id: 35, name: "Hugo Nash", email: "hugo.nash@example.com" },
  { id: 36, name: "Isla Moon", email: "isla.moon@example.com" },
  { id: 37, name: "Jonas Pike", email: "jonas.pike@example.com" },
  { id: 38, name: "Kylie Snow", email: "kylie.snow@example.com" },
  { id: 39, name: "Liam Wolf", email: "liam.wolf@example.com" },
  { id: 40, name: "Maya Frost", email: "maya.frost@example.com" },
  { id: 41, name: "Noah Grant", email: "noah.grant@example.com" },
  { id: 42, name: "Olivia Reed", email: "olivia.reed@example.com" },
  { id: 43, name: "Ethan Brooks", email: "ethan.brooks@example.com" },
  { id: 44, name: "Sophia Hayes", email: "sophia.hayes@example.com" },
  { id: 45, name: "Mason Price", email: "mason.price@example.com" },
  { id: 46, name: "Ava West", email: "ava.west@example.com" },
  { id: 47, name: "Logan Fox", email: "logan.fox@example.com" },
  { id: 48, name: "Mia Lane", email: "mia.lane@example.com" },
  { id: 49, name: "Lucas Dean", email: "lucas.dean@example.com" },
  { id: 50, name: "Ella Shaw", email: "ella.shaw@example.com" },
  { id: 51, name: "Benjamin Cole", email: "benjamin.cole@example.com" },
  { id: 52, name: "Chloe Hunt", email: "chloe.hunt@example.com" },
  { id: 53, name: "Alexander Ray", email: "alexander.ray@example.com" },
  { id: 54, name: "Amelia Ford", email: "amelia.ford@example.com" },
  { id: 55, name: "Elijah Moss", email: "elijah.moss@example.com" },
  { id: 56, name: "Harper Neal", email: "harper.neal@example.com" },
  { id: 57, name: "James King", email: "james.king@example.com" },
  { id: 58, name: "Lily Webb", email: "lily.webb@example.com" },
  { id: 59, name: "William Nash", email: "william.nash@example.com" },
  { id: 60, name: "Emily Frost", email: "emily.frost@example.com" },
  { id: 61, name: "Henry Blake", email: "henry.blake@example.com" },
  { id: 62, name: "Scarlett Lowe", email: "scarlett.lowe@example.com" },
  { id: 63, name: "Jack Stone", email: "jack.stone@example.com" },
  { id: 64, name: "Grace Boyd", email: "grace.boyd@example.com" },
  { id: 65, name: "Samuel Holt", email: "samuel.holt@example.com" },
  { id: 66, name: "Victoria Moon", email: "victoria.moon@example.com" },
  { id: 67, name: "Matthew Pike", email: "matthew.pike@example.com" },
  { id: 68, name: "Zoe Snow", email: "zoe.snow@example.com" },
  { id: 69, name: "David Wolf", email: "david.wolf@example.com" },
  { id: 70, name: "Layla Frost", email: "layla.frost@example.com" },
  { id: 71, name: "Joseph Grant", email: "joseph.grant@example.com" },
  { id: 72, name: "Penelope Reed", email: "penelope.reed@example.com" },
  { id: 73, name: "Sebastian Brooks", email: "sebastian.brooks@example.com" },
  { id: 74, name: "Aria Hayes", email: "aria.hayes@example.com" },
  { id: 75, name: "Daniel Price", email: "daniel.price@example.com" },
  { id: 76, name: "Madison West", email: "madison.west@example.com" },
  { id: 77, name: "Carter Fox", email: "carter.fox@example.com" },
  { id: 78, name: "Avery Lane", email: "avery.lane@example.com" },
  { id: 79, name: "Wyatt Dean", email: "wyatt.dean@example.com" },
  { id: 80, name: "Sofia Shaw", email: "sofia.shaw@example.com" },
  { id: 81, name: "Julian Cole", email: "julian.cole@example.com" },
  { id: 82, name: "Camila Hunt", email: "camila.hunt@example.com" },
  { id: 83, name: "Levi Ray", email: "levi.ray@example.com" },
  { id: 84, name: "Hannah Ford", email: "hannah.ford@example.com" },
  { id: 85, name: "Gabriel Moss", email: "gabriel.moss@example.com" },
  { id: 86, name: "Nora Neal", email: "nora.neal@example.com" },
  { id: 87, name: "Anthony King", email: "anthony.king@example.com" },
  { id: 88, name: "Stella Webb", email: "stella.webb@example.com" },
  { id: 89, name: "Andrew Nash", email: "andrew.nash@example.com" },
  { id: 90, name: "Ellie Frost", email: "ellie.frost@example.com" },
  { id: 91, name: "Joshua Blake", email: "joshua.blake@example.com" },
  { id: 92, name: "Aurora Lowe", email: "aurora.lowe@example.com" },
  { id: 93, name: "Ryan Stone", email: "ryan.stone@example.com" },
  { id: 94, name: "Savannah Boyd", email: "savannah.boyd@example.com" },
  { id: 95, name: "Luke Holt", email: "luke.holt@example.com" },
  { id: 96, name: "Brooklyn Moon", email: "brooklyn.moon@example.com" },
  { id: 97, name: "Nathan Pike", email: "nathan.pike@example.com" },
  { id: 98, name: "Paisley Snow", email: "paisley.snow@example.com" },
  { id: 99, name: "Isaac Wolf", email: "isaac.wolf@example.com" },
  { id: 100, name: "Audrey Frost", email: "audrey.frost@example.com" },
  { id: 101, name: "Lincoln Grant", email: "lincoln.grant@example.com" },
  { id: 102, name: "Claire Reed", email: "claire.reed@example.com" },
  { id: 103, name: "Hudson Brooks", email: "hudson.brooks@example.com" },
  { id: 104, name: "Violet Hayes", email: "violet.hayes@example.com" },
  { id: 105, name: "Grayson Price", email: "grayson.price@example.com" },
  { id: 106, name: "Riley West", email: "riley.west@example.com" },
  { id: 107, name: "Dylan Fox", email: "dylan.fox@example.com" },
  { id: 108, name: "Lucy Lane", email: "lucy.lane@example.com" },
  { id: 109, name: "Jaxon Dean", email: "jaxon.dean@example.com" },
  { id: 110, name: "Mila Shaw", email: "mila.shaw@example.com" },
  { id: 111, name: "Asher Cole", email: "asher.cole@example.com" },
  { id: 112, name: "Hazel Hunt", email: "hazel.hunt@example.com" },
  { id: 113, name: "Leo Ray", email: "leo.ray@example.com" },
  { id: 114, name: "Aurora Ford", email: "aurora.ford@example.com" },
  { id: 115, name: "Easton Moss", email: "easton.moss@example.com" },
  { id: 116, name: "Lillian Neal", email: "lillian.neal@example.com" },
  { id: 117, name: "Christopher King", email: "christopher.king@example.com" },
  { id: 118, name: "Addison Webb", email: "addison.webb@example.com" },
  { id: 119, name: "Eli Nash", email: "eli.nash@example.com" },
  { id: 120, name: "Samantha Frost", email: "samantha.frost@example.com" },
  { id: 121, name: "Aaron Blake", email: "aaron.blake@example.com" },
  { id: 122, name: "Aaliyah Lowe", email: "aaliyah.lowe@example.com" },
  { id: 123, name: "Charles Stone", email: "charles.stone@example.com" },
  { id: 124, name: "Elena Boyd", email: "elena.boyd@example.com" },
  { id: 125, name: "Isaiah Holt", email: "isaiah.holt@example.com" },
  { id: 126, name: "Maya Moon", email: "maya.moon@example.com" },
  { id: 127, name: "Thomas Pike", email: "thomas.pike@example.com" },
  { id: 128, name: "Bella Snow", email: "bella.snow@example.com" },
  { id: 129, name: "Wyatt Wolf", email: "wyatt.wolf@example.com" },
  { id: 130, name: "Anna Frost", email: "anna.frost@example.com" },
  { id: 131, name: "Julian Grant", email: "julian.grant@example.com" },
  { id: 132, name: "Savannah Reed", email: "savannah.reed@example.com" },
  { id: 133, name: "Evan Brooks", email: "evan.brooks@example.com" },
  { id: 134, name: "Leah Hayes", email: "leah.hayes@example.com" },
  { id: 135, name: "Nathan Price", email: "nathan.price@example.com" },
  { id: 136, name: "Aubrey West", email: "aubrey.west@example.com" },
  { id: 137, name: "Hunter Fox", email: "hunter.fox@example.com" },
  { id: 138, name: "Stella Lane", email: "stella.lane@example.com" },
  { id: 139, name: "Lincoln Dean", email: "lincoln.dean@example.com" },
  { id: 140, name: "Ellie Shaw", email: "ellie.shaw@example.com" },
];

// mock function to simulate fetching users from an API
export const getUsers = async (
  page: number,
  perPage: number,
  search?: string
): Promise<{ users: typeof users; count: number }> => {
  let filtered = users;
  if (search) {
    const s = search.toLowerCase();
    filtered = users.filter(
      (u) =>
        u.name.toLowerCase().includes(s) || u.email.toLowerCase().includes(s)
    );
  }
  const start = (page - 1) * perPage;
  const end = start + perPage;
  const paginated = filtered.slice(start, end);
  const count = filtered.length;
  return Promise.resolve({ users: paginated, count });
};
